name: Claude Auto PR Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create auto-review comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // PR作成時のみ自動レビューコメントを作成
            if (context.payload.action === 'opened') {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: '@claude このPRをレビューしてください。コードの品質、潜在的なバグ、改善提案について確認をお願いします。'
              });
            }